name: docker

on:
#  release:
#    types: [created]
  push:
    branches: [docker]

jobs:
    deploy:
        name: Build Docker image
        runs-on: ubuntu-latest

        steps:
          - name: Check out conclock-server
            uses: actions/checkout@v4
            with:
              repository: 'lladnaar/conclock-server'
              ref: 'latest'
              
          - name: Check out conclock-client
            uses: actions/checkout@v4
            with:
              path: 'app'

          - name: Set up Node
            uses: actions/setup-node@v4
            with:
              node-version: 24

          - name: Install dependencies
            run: npm ci

          - name: Build image
            run: npm run build
